# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: haberdasher.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("haberdasher.proto", :syntax => :proto3) do
    add_message "Size" do
      optional :inches, :int32, 1
    end
    add_message "Hat" do
      optional :inches, :int32, 1
      optional :color, :string, 2
      optional :name, :string, 3
    end
    add_message "HatList" do
      repeated :hats, :message, 1, "Hat"
    end
  end
end

Size = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Size").msgclass
Hat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Hat").msgclass
HatList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HatList").msgclass
